
num_threads = 16

[ws]
port = 51012
host = "127.0.0.1"

[rpc]
port = 51011
host = "127.0.0.1"

[observer.binance]
# symbols_path = "/home/keyg/.exch_observer/all_binance_tokens.csv"
symbols_path = "/home/keyg/.exch_observer/binance_tokens.csv"
allowed_symbols = [ "usdt", "busd", "cfx", "stx", "agix", "btc", "ltc", "xrp", "shib", "doge", "sol", "ada", "eth", "apt", "matic", "dot", "bnb" ]
# allowed_symbols = [ "USDT", "BUSD", "CFX", "STX", "AGIX", "BTC", "LTC", "XRP", "SHIB", "DOGE", "SOL", "ADA", "ETH", "APT", "MATIC", "DOT", "BNB" ]
enable = true
ws_port = 51013

[observer.huobi]
# symbols_path = "/home/keyg/.exch_observer/all_huobi_tokens.csv"
symbols_path = "/home/keyg/.exch_observer/huobi_tokens.csv"
allowed_symbols = [ "usdt", "btc", "eth", "bnb", "sol", "dot" ]
enable = true
ws_port = 51014

[observer.kraken]
# symbols_path = "/home/keyg/.exch_observer/all_kraken_tokens.csv"
symbols_path = "/home/keyg/.exch_observer/kraken_tokens.csv"
allowed_symbols = [ "USD", "EUR", "SOL", "JPY", "USDC", "ETH", "XBT", "MANA" ]
enable = true
ws_port = 51015
