[package]
name = "exch_observer_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exch_observer_types = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
