name: "Build setup"
description: "Installs necessary packages to build exch_observer"

runs:
  using: composite

  steps:
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
